# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # runs during prebuild
  - init: |
      echo 'init script' 
      sudo apt install rsync --assume-yes
      nvm install 14
      mkdir ~/.lnstx
      cp boltz.conf ~/.lnstx/boltz.conf
      echo "bronze large spike canoe youth crucial seminar awkward allow frozen client math" > ~/.lnstx/seed.dat
      npm i
      npm run docker:regtest
      sed -i 's/sslEnabled: true/sslEnabled: false/g' lib/Config.ts
    # git stash
    command: |
      npm run dev
  - init: |
      docker ps
    # sleep 60
    command: >
      alias lnclibtc2='docker exec -it regtest lncli --rpcserver=127.0.0.1:10011 --tlscertpath=/root/.lnd-btc2/tls.cert --macaroonpath=/root/.lnd-btc2/data/chain/bitcoin/regtest/admin.macaroon'
      alias lnclibtc1='docker exec -it regtest lncli --rpcserver=127.0.0.1:10009 --tlscertpath=/root/.lnd-btc/tls.cert --macaroonpath=/root/.lnd-btc/data/chain/bitcoin/regtest/admin.macaroon'
      alias btccli='docker exec -it regtest /usr/bin/bitcon-cli '
      lnclibtc2 newaddress p2wkh
      bitcoin-cli send '{"bcrt1q93rsj05zw3pvf8pa4gpjaypy5x5mqws49as43t":10}'
      bitcoin-cli -regtest -generate 1
    # docker exec -it regtest bash
    # echo "alias lnclibtc2='lncli --rpcserver=127.0.0.1:10011 --tlscertpath=/root/.lnd-btc/tls.cert --macaroonpath=/root/.lnd-btc/data/chain/bitcoin/regtest/admin.macaroon'"
    # docker stop regtest &&  docker rm regtest && npm run docker:regtest
  - init: |
      npm i -g shx rimraf 
      npm run stacks:mocknet
      sleep 180
    command: |
      npm run stacks:fund
      SIGNER=ST27SD3H5TTZXPBFXHN1ZNMFJ3HNE2070QX7ZN4FF npm run stacks:fund:signer
      sleep 5
      SIGNER=ST1N28QCRR03EW37S470PND4SPECCXQ22ZZHF97GP npm run stacks:fund:signer
      sleep 10
      npm run stacks:deploy
    # seed set manually and funded ST1N28QCRR03EW37S470PND4SPECCXQ22ZZHF97GP as the operator account
  - init: |
        git clone https://github.com/pseudozach/lnstxbridge-frontend.git /workspace/lnstxbridge-frontend
        export REACT_APP_BOLTZ_API=https://9002-${GITPOD_WORKSPACE_URL:8}
        export REACT_APP_STACKS_API=https://3999-${GITPOD_WORKSPACE_URL:8}
        gp env REACT_APP_BOLTZ_API=$REACT_APP_BOLTZ_API
        cd /workspace/lnstxbridge-frontend
        sed -i 's/HTTPS=true/HTTPS=false/g' .env
        sed -i 's/PORT=443/PORT=8888/g' .env
        sed -i 's/REACT_APP_STACKS_NETWORK_TYPE=mainnet/REACT_APP_STACKS_NETWORK_TYPE=mocknet/g' .env
        sed -i 's#REACT_APP_BOLTZ_API=https://lnswap.org:9002#REACT_APP_BOLTZ_API=${REACT_APP_BOLTZ_API}#g' .env
        npm i    
      # sed -i "s#new StacksMocknet()#new StacksMocknet({url: '$REACT_APP_STACKS_API'})#g"  /workspace/lnstxbridge-frontend/src/views/swap/steps/sendTransaction.js
      # sed -i "s#new StacksMocknet()#new StacksMocknet({url: '$REACT_APP_STACKS_API'})#g" /workspace/lnstxbridge-frontend/src/views/reverse/steps/lockingFunds.js
      # git stash
    command: npm run start
  - init: brew install clarinet
    command: clarinet test
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 3999
    onOpen: open-browser
    visibility: public
  - port: 9002
    onOpen: ignore
    visibility: public
  - port: 8888
    onOpen: open-browser
    visibility: public