# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # runs during prebuild
  - init: |
      echo 'init script' 
      sudo apt install rsync --assume-yes
      nvm install 14
      mkdir ~/.boltz
      cp boltz.conf ~/.boltz/boltz.conf
      npm i
      sed -i 's/sslEnabled: true/sslEnabled: false/g' lib/Config.ts
    command: npm run dev
  - init: |
      npm run docker:regtest
    command: >
      docker exec -it regtest bash
      echo "alias lnclibtc2='lncli --rpcserver=127.0.0.1:10011 --tlscertpath=/root/.lnd-btc/tls.cert --macaroonpath=/root/.lnd-btc/data/chain/bitcoin/regtest/admin.macaroon'"
  - init: |
      npm i -g shx rimraf 
      npm run stacks:mocknet
      sleep 180
    command: |
      npm run stacks:fund
      SIGNER=ST27SD3H5TTZXPBFXHN1ZNMFJ3HNE2070QX7ZN4FF npm run stacks:fund:signer
      sleep 10
      npm run stacks:deploy
    # fund the operator account as well!
    # SIGNER=ST3P4DRFSWGD6S58VQ4QWEHM1JW34XM6WNVYZAH3N npm run stacks:fund:signer
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 3999
    onOpen: open-preview
    visibility: public
  - port: 9001
    onOpen: open-preview
    visibility: public
