[node]
#name = "helium-node"
rpc_bind = "0.0.0.0:20443"
bootstrap_node = "047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@testnet.stacks.co:20444"
p2p_bind = "0.0.0.0:20444"
wait_time_for_microblocks = 10000
#working_dir = "/tmp/stackschainstate"
working_dir = "/tmp/stacks-node-1630122653835"

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "bitcoind.testnet.stacks.co"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 18332
peer_port = 18333

[[events_observer]]
endpoint = "127.0.0.1:3700"
events_keys = [
  "*"
]
