name: Docker Image CI

on:
  push:
    branches:    
      - main
      - 'dockerization'
  pull_request:
    branches: [ main ]

# # works for amd64
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: login to docker hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#     - name: Build the Docker image
#       run: docker buildx build --push --tag pseudozach/lnstxbridge:$(date +%s) --tag pseudozach/lnstxbridge:latest --platform linux/amd64 .

# arm64 - rpi
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            pseudozach/lnstxbridge:latest
            pseudozach/lnstxbridge:$(date +%s)